/* tslint:disable */
/* eslint-disable */
/**
 * Aineistopalvelu API v1
 *   Palvelu vastaa seuraavista kohdeluokista:  | Nimi | Tekninen nimi | OID-prefix | Versioitu | Schema | Sijaintityyppi | Sijaintitarkenne | | :--- | :--- | :--- | :---: | :---: | :---: | :---: | | Aineisto | aineisto/aineisto | 1.2.246.578.5.100 | ⬜ | 7 | - | - | | Dokumentti | aineisto/dokumentti | 1.2.246.578.5.199 | ⬜ | 2 | - | - | | Ladattava paketti | aineisto/ladattava-paketti | 1.2.246.578.5.102 | ⬜ | 1 | - | - | | Pakattu kansio | aineisto/pakattu-kansio | 1.2.246.578.5.101 | ⬜ | 1 | - | - | | Viittaus | aineisto/viittaus | 1.2.246.578.5.103 | ⬜ | 2 | - | - |
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

