projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - common/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - ./graphql/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: common/graphql/apiModel.ts
        docsFilePath: common/graphql
        region: eu-west-1
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
