#!/usr/bin/env sh

echo "Writing public environment variables to file /public/assets/__env.js..."

cat <<EOF > /app/public/assets/__env.js
window.__ENV = {
  VERSION: "$VERSION",
  ENVIRONMENT: "$ENVIRONMENT",
  VAYLA_EXTRANET_URL: "$VAYLA_EXTRANET_URL",
  VELHO_BASE_URL: "$VELHO_BASE_URL",
  AJANSIIRTO_SALLITTU: "$AJANSIIRTO_SALLITTU",
  REACT_APP_API_URL: "$VAYLA_EXREACT_APP_API_URLTRANET_URL",
  REACT_APP_API_KEY: "$REACT_APP_API_KEY",
  FRONTEND_DOMAIN_NAME: "$FRONTEND_DOMAIN_NAME",
  KEYCLOAK_CLIENT_ID: "$KEYCLOAK_CLIENT_ID",
  KEYCLOAK_DOMAIN: "$KEYCLOAK_DOMAIN",
  EVK_ACTIVATION_DATE: "$EVK_ACTIVATION_DATE",
};
EOF

echo "Starting the Nextjs application..."
exec "$@"