version: "3.8"
services:
  localstack:
    image: public.ecr.aws/localstack/localstack:2.0.2
    ports:
      - "4566-4584:4566-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,sts,cloudformation,ssm,s3,iam,kms,events,lambda,resource-groups
      - DEFAULT_REGION=eu-west-1
      - DEBUG=0
      # LS_LOG=trace
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST="unix:///var/run/docker.sock"
      - EXTRA_CORS_ALLOWED_ORIGINS=*
