import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div>
          <h1>Hello world!</h1>
        </div>
      </main>
    </div>
  );
}
