/* tslint:disable */
/* eslint-disable */
/**
 * Projektirekisteri API v2
 * Projektirekisteri API v2  Palvelu vastaa seuraavista kohdeluokista:  - Projekti (tekninen nimi: projekti/projekti, oid-prefix: 1.2.246.578.5.1)  - Projektijoukko (tekninen nimi: projekti/projektijoukko, oid-prefix: 1.2.246.578.5.3)  - Toimeksianto (tekninen nimi: projekti/toimeksianto, oid-prefix: 1.2.246.578.5.2)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

