/* tslint:disable */
/* eslint-disable */
/**
 * Projektirekisteri API v2
 *   Palvelu vastaa seuraavista kohdeluokista:  | Nimi | Tekninen nimi | OID-prefix | Versioitu | Schema | Sijaintityyppi | Sijaintitarkenne | | :--- | :--- | :--- | :---: | :---: | :---: | :---: | | Projekti | projekti/projekti | 1.2.246.578.5.1 | ⬜ | 9 | valisijaintikokoelma | - | | Projektijoukko | projekti/projektijoukko | 1.2.246.578.5.3 | ⬜ | 5 | - | - | | Toimeksianto | projekti/toimeksianto | 1.2.246.578.5.2 | ⬜ | 6 | - | - |
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

