import { PublishOrExpireEventType } from "./projektiScheduleManager";

export enum SqsEventType {
  SYNCHRONIZE = "SYNCHRONIZE",
  END_NAHTAVILLAOLO_AINEISTOMUOKKAUS = "END_NAHTAVILLAOLO_AINEISTOMUOKKAUS",
  END_HYVAKSYMISPAATOS_AINEISTOMUOKKAUS = "END_HYVAKSYMISPAATOS_AINEISTOMUOKKAUS",
  END_JATKOPAATOS1_AINEISTOMUOKKAUS = "END_JATKOPAATOS1_AINEISTOMUOKKAUS",
  END_JATKOPAATOS2_AINEISTOMUOKKAUS = "END_JATKOPAATOS2_AINEISTOMUOKKAUS",
  AINEISTO_CHANGED = "AINEISTO_CHANGED",
  FILES_CHANGED = "FILES_CHANGED",
  AINEISTO_AND_FILES_CHANGED = "AINEISTO_AND_FILES_CHANGED",
  ZIP_NAHTAVILLAOLO = "ZIP_NAHTAVILLAOLO",
  ZIP_LAUSUNTOPYYNNOT = "ZIP_LAUSUNTOPYYNNOT",
  ZIP_LAUSUNTOPYYNNON_TAYDENNYKSET = "ZIP_LAUSUNTOPYYNNON_TAYDENNYKSET",
  ZIP_LAUSUNTOPYYNTO = "ZIP_LAUSUNTOPYYNTO",
  ONE_MONTH_TO_INACTIVE = "ONE_MONTH_TO_INACTIVE",
}

export type SqsEvent = {
  type: SqsEventType;
  oid: string;
  uuid?: string; //ZIP_LAUSUNTOPYYNTO -eventiä varten
  scheduleName?: string;
  retriesLeft?: number;
  reason?: string;
  date?: string;
  approvalType?: PublishOrExpireEventType;
};
