export enum SqsEventType {
  SYNCHRONIZE_AND_INDEX = "SYNCHRONIZE_AND_INDEX",
  END_NAHTAVILLAOLO_AINEISTOMUOKKAUS = "END_NAHTAVILLAOLO_AINEISTOMUOKKAUS",
  END_HYVAKSYMISPAATOS_AINEISTOMUOKKAUS = "END_HYVAKSYMISPAATOS_AINEISTOMUOKKAUS",
  END_JATKOPAATOS1_AINEISTOMUOKKAUS = "END_JATKOPAATOS1_AINEISTOMUOKKAUS",
  END_JATKOPAATOS2_AINEISTOMUOKKAUS = "END_JATKOPAATOS2_AINEISTOMUOKKAUS",
  VUOROVAIKUTUS_AINEISTO_CHANGED = "VUOROVAIKUTUS_AINEISTO_CHANGED",
  VUOROVAIKUTUS_JULKAISU_AINEISTO_CHANGED = "VUOROVAIKUTUS_JULKAISU_AINEISTO_CHANGED",
  NAHTAVILLAOLO_AINEISTO_NAHTAVILLA_CHANGED = "NAHTAVILLAOLO_AINEISTO_NAHTAVILLA_CHANGED",
  LISA_AINEISTO_CHANGED = "LISA_AINEISTO_CHANGED",
  MUISTUTUKSET_CHANGED = "MUISTUTUKSET_CHANGED",
  MUU_AINEISTO_CHANGED = "MUU_AINEISTO_CHANGED",
  HYVAKSYMISVAIHE_AINEISTO_NAHTAVILLA_CHANGED = "HYVAKSYMISVAIHE_AINEISTO_NAHTAVILLA_CHANGED",
  JATKOPAATOS1_AINEISTO_NAHTAVILLA_CHANGED = "JATKOPAATOS1_AINEISTO_NAHTAVILLA_CHANGED",
  JATKOPAATOS2_AINEISTO_NAHTAVILLA_CHANGED = "JATKOPAATOS2_AINEISTO_NAHTAVILLA_CHANGED",
  HYVAKSYMISVAIHE_HYVAKSYMISPAATOS_CHANGED = "HYVAKSYMISVAIHE_HYVAKSYMISPAATOS_CHANGED",
  JATKOPAATOS1_HYVAKSYMISPAATOS_CHANGED = "JATKOPAATOS1_HYVAKSYMISPAATOS_CHANGED",
  JATKOPAATOS2_HYVAKSYMISPAATOS_CHANGED = "JATKOPAATOS2_HYVAKSYMISPAATOS_CHANGED",
  AINEISTO_CHANGED = "AINEISTO_CHANGED",
  TIEDOSTOT_CHANGED = "TIEDOSTOT_CHANGED",
  ZIP_NAHTAVILLAOLO = "ZIP_NAHTAVILLAOLO",
  ZIP_LAUSUNTOPYYNNOT = "ZIP_LAUSUNTOPYYNNOT",
  ZIP_LAUSUNTOPYYNNON_TAYDENNYS = "ZIP_LAUSUNTOPYYNNON_TAYDENNYS",
  ZIP_LAUSUNTOPYYNTO = "ZIP_LAUSUNTOPYYNTO",
}

export type SqsEvent = {
  type: SqsEventType;
  oid: string;
  uuid?: string; // Lausuntopyyntöjen ja lausuntopyyntöjen täydennysten identifioimiseen
  id?: number; // VuorovaikutusKierrosJulkaisujen identifioimiseen
  scheduleName?: string;
  retriesLeft?: number;
  reason?: string;
  date?: string;
};
