/* tslint:disable */
/* eslint-disable */
/**
 * Hakupalvelu API v2
 * Hakupalvelu API v2
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface HakulausekeAsetukset {
    'aggregaatiot'?: Array<object>;
    'liitoshaku'?: boolean;
    'oid-haku'?: boolean;
    'palautettavat-kentat'?: Array<Array<string>>;
    'pilko-tiekohdehaun-lisarajauksilla?'?: boolean;
    'arvojarjestys?'?: boolean;
    'koko'?: number;
    'pilkkovat-polut'?: Array<Array<string>>;
    'alkaen'?: number;
    'poistettavat-kentat'?: Array<Array<string>>;
    'samalla-kaistalla'?: boolean;
    'geometriat'?: Array<HakulausekeAsetuksetGeometriatEnum>;
    'poista-duplikaatit?'?: boolean;
    'tilannepaivamaara'?: string;
    'tyyppi'?: HakulausekeAsetuksetTyyppiEnum;
    'jarjesta'?: Array<Array<object>>;
}

export const HakulausekeAsetuksetGeometriatEnum = {
    keskilinjageometria_wgs84: 'keskilinjageometria-wgs84',
    keskilinjageometria: 'keskilinjageometria',
    keskilinjageometria2: 'keskilinjageometria',
    keskilinjageometria_wgs842: 'keskilinjageometria-wgs84'
} as const;

export type HakulausekeAsetuksetGeometriatEnum = typeof HakulausekeAsetuksetGeometriatEnum[keyof typeof HakulausekeAsetuksetGeometriatEnum];
export const HakulausekeAsetuksetTyyppiEnum = {
    tieosuushaku: 'tieosuushaku',
    kohdeluokkahaku: 'kohdeluokkahaku',
    kohdeluokkahaku2: 'kohdeluokkahaku',
    tieosuushaku2: 'tieosuushaku'
} as const;

export type HakulausekeAsetuksetTyyppiEnum = typeof HakulausekeAsetuksetTyyppiEnum[keyof typeof HakulausekeAsetuksetTyyppiEnum];

export interface HakulausekeKysely {
    'kohdeluokat': Array<string>;
    'asetukset': HakulausekeAsetukset;
    'lauseke'?: object;
}
export interface HakulausekeLisarajaukset {
    'kohdeluokat': Array<string>;
    'lauseke': object;
    'palautettavat-kentat'?: Array<Array<string>>;
}
export interface HakulausekeLisarajausKysely {
    'kohdeluokat': Array<string>;
    'asetukset': HakulausekeAsetukset;
    'lauseke'?: object;
    'lisarajaukset'?: HakulausekeLisarajaukset;
}
export interface HakupalveluSpecHakuspecTaustahakuTila {
    'hakutunniste': string;
    'tila': string;
    'alkuaika': string;
    'muokkausaika': string;
    'hakutunniste-voimassa': number;
    'metrit'?: number | null;
    'tagi'?: string;
    'osumia'?: number;
}
export interface HakupalveluSpecHakuspecVientiListaa {
    'tunniste'?: string;
}
export interface HakupalveluSpecHakuspecVientiNouda {
    'tunniste': string;
}
export interface HakupalveluSpecHakuspecVientiVie {
    'hakulauseke': HakupalveluSpecHakuspecVientiVieHakulauseke;
    'tiedostonimi': string;
    'tiedostomuoto': string;
}
export interface HakupalveluSpecHakuspecVientiVie1 {
    'hakutunniste': string;
    'tiedostonimi': string;
    'tiedostomuoto': string;
    'geometriat': Array<string>;
    'taulukon-sarakkeet': Array<string>;
}
export interface HakupalveluSpecHakuspecVientiVieHakulauseke {
    'kohdeluokat': Array<string>;
    'asetukset': HakulausekeAsetukset;
    'lauseke'?: object;
}

/**
 * HakuApi - axios parameter creator
 */
export const HakuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Hae ehdot täyttävien kohdeluokkien lukumäärä
         * @param {HakulausekeKysely} hakulausekeKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatLukumaaraPost: async (hakulausekeKysely: HakulausekeKysely, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakulausekeKysely' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuKohdeluokatLukumaaraPost', 'hakulausekeKysely', hakulausekeKysely)
            const localVarPath = `/hakupalvelu/api/v2/haku/kohdeluokat/lukumaara`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakulausekeKysely, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia
         * @param {HakulausekeKysely} hakulausekeKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatPost: async (hakulausekeKysely: HakulausekeKysely, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakulausekeKysely' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuKohdeluokatPost', 'hakulausekeKysely', hakulausekeKysely)
            const localVarPath = `/hakupalvelu/api/v2/haku/kohdeluokat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakulausekeKysely, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listaa aiemmin viedyt hakutulokset
         * @param {HakupalveluSpecHakuspecVientiListaa} hakupalveluSpecHakuspecVientiListaa 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiListaaPost: async (hakupalveluSpecHakuspecVientiListaa: HakupalveluSpecHakuspecVientiListaa, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakupalveluSpecHakuspecVientiListaa' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuKohdeluokatVientiListaaPost', 'hakupalveluSpecHakuspecVientiListaa', hakupalveluSpecHakuspecVientiListaa)
            const localVarPath = `/hakupalvelu/api/v2/haku/kohdeluokat/vienti/listaa`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakupalveluSpecHakuspecVientiListaa, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Nouda valmistunut hakutulos
         * @param {HakupalveluSpecHakuspecVientiNouda} hakupalveluSpecHakuspecVientiNouda 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiNoudaPost: async (hakupalveluSpecHakuspecVientiNouda: HakupalveluSpecHakuspecVientiNouda, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakupalveluSpecHakuspecVientiNouda' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuKohdeluokatVientiNoudaPost', 'hakupalveluSpecHakuspecVientiNouda', hakupalveluSpecHakuspecVientiNouda)
            const localVarPath = `/hakupalvelu/api/v2/haku/kohdeluokat/vienti/nouda`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakupalveluSpecHakuspecVientiNouda, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia & vie
         * @param {HakupalveluSpecHakuspecVientiVie} hakupalveluSpecHakuspecVientiVie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiViePost: async (hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakupalveluSpecHakuspecVientiVie' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuKohdeluokatVientiViePost', 'hakupalveluSpecHakuspecVientiVie', hakupalveluSpecHakuspecVientiVie)
            const localVarPath = `/hakupalvelu/api/v2/haku/kohdeluokat/vienti/vie`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakupalveluSpecHakuspecVientiVie, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hae tunnisteella osumat & vie
         * @param {HakupalveluSpecHakuspecVientiVie1} hakupalveluSpecHakuspecVientiVie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost: async (hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakupalveluSpecHakuspecVientiVie' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost', 'hakupalveluSpecHakuspecVientiVie', hakupalveluSpecHakuspecVientiVie)
            const localVarPath = `/hakupalvelu/api/v2/haku/kohdeluokat/vienti/vie-tunnisteella`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakupalveluSpecHakuspecVientiVie, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä tieosuuksia CLJ toteutus
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuTieosuudetPost: async (hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakulausekeLisarajausKysely' is not null or undefined
            assertParamExists('hakupalveluApiV2HakuTieosuudetPost', 'hakulausekeLisarajausKysely', hakulausekeLisarajausKysely)
            const localVarPath = `/hakupalvelu/api/v2/haku/tieosuudet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakulausekeLisarajausKysely, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HakuApi - functional programming interface
 */
export const HakuApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HakuApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Hae ehdot täyttävien kohdeluokkien lukumäärä
         * @param {HakulausekeKysely} hakulausekeKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuKohdeluokatLukumaaraPost(hakulausekeKysely: HakulausekeKysely, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuKohdeluokatLukumaaraPost(hakulausekeKysely, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuKohdeluokatLukumaaraPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia
         * @param {HakulausekeKysely} hakulausekeKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuKohdeluokatPost(hakulausekeKysely: HakulausekeKysely, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuKohdeluokatPost(hakulausekeKysely, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuKohdeluokatPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Listaa aiemmin viedyt hakutulokset
         * @param {HakupalveluSpecHakuspecVientiListaa} hakupalveluSpecHakuspecVientiListaa 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuKohdeluokatVientiListaaPost(hakupalveluSpecHakuspecVientiListaa: HakupalveluSpecHakuspecVientiListaa, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuKohdeluokatVientiListaaPost(hakupalveluSpecHakuspecVientiListaa, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuKohdeluokatVientiListaaPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Nouda valmistunut hakutulos
         * @param {HakupalveluSpecHakuspecVientiNouda} hakupalveluSpecHakuspecVientiNouda 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuKohdeluokatVientiNoudaPost(hakupalveluSpecHakuspecVientiNouda: HakupalveluSpecHakuspecVientiNouda, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuKohdeluokatVientiNoudaPost(hakupalveluSpecHakuspecVientiNouda, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuKohdeluokatVientiNoudaPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia & vie
         * @param {HakupalveluSpecHakuspecVientiVie} hakupalveluSpecHakuspecVientiVie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuKohdeluokatVientiViePost(hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuKohdeluokatVientiViePost(hakupalveluSpecHakuspecVientiVie, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuKohdeluokatVientiViePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hae tunnisteella osumat & vie
         * @param {HakupalveluSpecHakuspecVientiVie1} hakupalveluSpecHakuspecVientiVie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost(hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost(hakupalveluSpecHakuspecVientiVie, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä tieosuuksia CLJ toteutus
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2HakuTieosuudetPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2HakuTieosuudetPost(hakulausekeLisarajausKysely, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HakuApi.hakupalveluApiV2HakuTieosuudetPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HakuApi - factory interface
 */
export const HakuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HakuApiFp(configuration)
    return {
        /**
         * 
         * @summary Hae ehdot täyttävien kohdeluokkien lukumäärä
         * @param {HakulausekeKysely} hakulausekeKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatLukumaaraPost(hakulausekeKysely: HakulausekeKysely, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuKohdeluokatLukumaaraPost(hakulausekeKysely, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia
         * @param {HakulausekeKysely} hakulausekeKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatPost(hakulausekeKysely: HakulausekeKysely, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuKohdeluokatPost(hakulausekeKysely, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listaa aiemmin viedyt hakutulokset
         * @param {HakupalveluSpecHakuspecVientiListaa} hakupalveluSpecHakuspecVientiListaa 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiListaaPost(hakupalveluSpecHakuspecVientiListaa: HakupalveluSpecHakuspecVientiListaa, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuKohdeluokatVientiListaaPost(hakupalveluSpecHakuspecVientiListaa, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Nouda valmistunut hakutulos
         * @param {HakupalveluSpecHakuspecVientiNouda} hakupalveluSpecHakuspecVientiNouda 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiNoudaPost(hakupalveluSpecHakuspecVientiNouda: HakupalveluSpecHakuspecVientiNouda, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuKohdeluokatVientiNoudaPost(hakupalveluSpecHakuspecVientiNouda, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia & vie
         * @param {HakupalveluSpecHakuspecVientiVie} hakupalveluSpecHakuspecVientiVie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiViePost(hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuKohdeluokatVientiViePost(hakupalveluSpecHakuspecVientiVie, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hae tunnisteella osumat & vie
         * @param {HakupalveluSpecHakuspecVientiVie1} hakupalveluSpecHakuspecVientiVie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost(hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie1, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost(hakupalveluSpecHakuspecVientiVie, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä tieosuuksia CLJ toteutus
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2HakuTieosuudetPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2HakuTieosuudetPost(hakulausekeLisarajausKysely, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HakuApi - object-oriented interface
 */
export class HakuApi extends BaseAPI {
    /**
     * 
     * @summary Hae ehdot täyttävien kohdeluokkien lukumäärä
     * @param {HakulausekeKysely} hakulausekeKysely 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuKohdeluokatLukumaaraPost(hakulausekeKysely: HakulausekeKysely, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuKohdeluokatLukumaaraPost(hakulausekeKysely, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hae ehdot täyttäviä kohdeluokkia
     * @param {HakulausekeKysely} hakulausekeKysely 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuKohdeluokatPost(hakulausekeKysely: HakulausekeKysely, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuKohdeluokatPost(hakulausekeKysely, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listaa aiemmin viedyt hakutulokset
     * @param {HakupalveluSpecHakuspecVientiListaa} hakupalveluSpecHakuspecVientiListaa 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuKohdeluokatVientiListaaPost(hakupalveluSpecHakuspecVientiListaa: HakupalveluSpecHakuspecVientiListaa, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuKohdeluokatVientiListaaPost(hakupalveluSpecHakuspecVientiListaa, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Nouda valmistunut hakutulos
     * @param {HakupalveluSpecHakuspecVientiNouda} hakupalveluSpecHakuspecVientiNouda 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuKohdeluokatVientiNoudaPost(hakupalveluSpecHakuspecVientiNouda: HakupalveluSpecHakuspecVientiNouda, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuKohdeluokatVientiNoudaPost(hakupalveluSpecHakuspecVientiNouda, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hae ehdot täyttäviä kohdeluokkia & vie
     * @param {HakupalveluSpecHakuspecVientiVie} hakupalveluSpecHakuspecVientiVie 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuKohdeluokatVientiViePost(hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuKohdeluokatVientiViePost(hakupalveluSpecHakuspecVientiVie, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hae tunnisteella osumat & vie
     * @param {HakupalveluSpecHakuspecVientiVie1} hakupalveluSpecHakuspecVientiVie 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost(hakupalveluSpecHakuspecVientiVie: HakupalveluSpecHakuspecVientiVie1, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuKohdeluokatVientiVieTunnisteellaPost(hakupalveluSpecHakuspecVientiVie, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hae ehdot täyttäviä tieosuuksia CLJ toteutus
     * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2HakuTieosuudetPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, options?: RawAxiosRequestConfig) {
        return HakuApiFp(this.configuration).hakupalveluApiV2HakuTieosuudetPost(hakulausekeLisarajausKysely, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TaustahakuApi - axios parameter creator
 */
export const TaustahakuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia taustahakuna
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {any} [tagi] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuKohdeluokatPost: async (hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakulausekeLisarajausKysely' is not null or undefined
            assertParamExists('hakupalveluApiV2TaustahakuKohdeluokatPost', 'hakulausekeLisarajausKysely', hakulausekeLisarajausKysely)
            const localVarPath = `/hakupalvelu/api/v2/taustahaku/kohdeluokat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tagi !== undefined) {
                localVarQueryParameter['tagi'] = tagi;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakulausekeLisarajausKysely, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä tieosia taustahakuna
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {any} [tagi] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTieosuudetPost: async (hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakulausekeLisarajausKysely' is not null or undefined
            assertParamExists('hakupalveluApiV2TaustahakuTieosuudetPost', 'hakulausekeLisarajausKysely', hakulausekeLisarajausKysely)
            const localVarPath = `/hakupalvelu/api/v2/taustahaku/tieosuudet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tagi !== undefined) {
                localVarQueryParameter['tagi'] = tagi;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(hakulausekeLisarajausKysely, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hakee tehtyjen taustahakujen tilat.
         * @param {string} [tagit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTilaGet: async (tagit?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/hakupalvelu/api/v2/taustahaku/tila`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tagit !== undefined) {
                localVarQueryParameter['tagit'] = tagit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hakee taustahaun tilan annetulle hakutunnistelle.
         * @param {string} hakutunniste 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTilaHakutunnisteGet: async (hakutunniste: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakutunniste' is not null or undefined
            assertParamExists('hakupalveluApiV2TaustahakuTilaHakutunnisteGet', 'hakutunniste', hakutunniste)
            const localVarPath = `/hakupalvelu/api/v2/taustahaku/tila/{hakutunniste}`
                .replace(`{${"hakutunniste"}}`, encodeURIComponent(String(hakutunniste)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Hakee taustahaun tulokset annetulle hakutunnistelle.
         * @param {string} hakutunniste 
         * @param {number} [alkupiste] 
         * @param {number} [maara] 
         * @param {boolean} [eiGeometrioita] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet: async (hakutunniste: string, alkupiste?: number, maara?: number, eiGeometrioita?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hakutunniste' is not null or undefined
            assertParamExists('hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet', 'hakutunniste', hakutunniste)
            const localVarPath = `/hakupalvelu/api/v2/taustahaku/tulokset/{hakutunniste}`
                .replace(`{${"hakutunniste"}}`, encodeURIComponent(String(hakutunniste)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (alkupiste !== undefined) {
                localVarQueryParameter['alkupiste'] = alkupiste;
            }

            if (maara !== undefined) {
                localVarQueryParameter['maara'] = maara;
            }

            if (eiGeometrioita !== undefined) {
                localVarQueryParameter['ei-geometrioita?'] = eiGeometrioita;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaustahakuApi - functional programming interface
 */
export const TaustahakuApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaustahakuApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia taustahakuna
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {any} [tagi] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2TaustahakuKohdeluokatPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HakupalveluSpecHakuspecTaustahakuTila>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2TaustahakuKohdeluokatPost(hakulausekeLisarajausKysely, tagi, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaustahakuApi.hakupalveluApiV2TaustahakuKohdeluokatPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä tieosia taustahakuna
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {any} [tagi] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2TaustahakuTieosuudetPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HakupalveluSpecHakuspecTaustahakuTila>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2TaustahakuTieosuudetPost(hakulausekeLisarajausKysely, tagi, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaustahakuApi.hakupalveluApiV2TaustahakuTieosuudetPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hakee tehtyjen taustahakujen tilat.
         * @param {string} [tagit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2TaustahakuTilaGet(tagit?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<object>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2TaustahakuTilaGet(tagit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaustahakuApi.hakupalveluApiV2TaustahakuTilaGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hakee taustahaun tilan annetulle hakutunnistelle.
         * @param {string} hakutunniste 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2TaustahakuTilaHakutunnisteGet(hakutunniste: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HakupalveluSpecHakuspecTaustahakuTila>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2TaustahakuTilaHakutunnisteGet(hakutunniste, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaustahakuApi.hakupalveluApiV2TaustahakuTilaHakutunnisteGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Hakee taustahaun tulokset annetulle hakutunnistelle.
         * @param {string} hakutunniste 
         * @param {number} [alkupiste] 
         * @param {number} [maara] 
         * @param {boolean} [eiGeometrioita] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet(hakutunniste: string, alkupiste?: number, maara?: number, eiGeometrioita?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet(hakutunniste, alkupiste, maara, eiGeometrioita, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaustahakuApi.hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TaustahakuApi - factory interface
 */
export const TaustahakuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaustahakuApiFp(configuration)
    return {
        /**
         * 
         * @summary Hae ehdot täyttäviä kohdeluokkia taustahakuna
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {any} [tagi] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuKohdeluokatPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options?: RawAxiosRequestConfig): AxiosPromise<HakupalveluSpecHakuspecTaustahakuTila> {
            return localVarFp.hakupalveluApiV2TaustahakuKohdeluokatPost(hakulausekeLisarajausKysely, tagi, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hae ehdot täyttäviä tieosia taustahakuna
         * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
         * @param {any} [tagi] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTieosuudetPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options?: RawAxiosRequestConfig): AxiosPromise<HakupalveluSpecHakuspecTaustahakuTila> {
            return localVarFp.hakupalveluApiV2TaustahakuTieosuudetPost(hakulausekeLisarajausKysely, tagi, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hakee tehtyjen taustahakujen tilat.
         * @param {string} [tagit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTilaGet(tagit?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<object>> {
            return localVarFp.hakupalveluApiV2TaustahakuTilaGet(tagit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hakee taustahaun tilan annetulle hakutunnistelle.
         * @param {string} hakutunniste 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTilaHakutunnisteGet(hakutunniste: string, options?: RawAxiosRequestConfig): AxiosPromise<HakupalveluSpecHakuspecTaustahakuTila> {
            return localVarFp.hakupalveluApiV2TaustahakuTilaHakutunnisteGet(hakutunniste, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Hakee taustahaun tulokset annetulle hakutunnistelle.
         * @param {string} hakutunniste 
         * @param {number} [alkupiste] 
         * @param {number} [maara] 
         * @param {boolean} [eiGeometrioita] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet(hakutunniste: string, alkupiste?: number, maara?: number, eiGeometrioita?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet(hakutunniste, alkupiste, maara, eiGeometrioita, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaustahakuApi - object-oriented interface
 */
export class TaustahakuApi extends BaseAPI {
    /**
     * 
     * @summary Hae ehdot täyttäviä kohdeluokkia taustahakuna
     * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
     * @param {any} [tagi] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2TaustahakuKohdeluokatPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options?: RawAxiosRequestConfig) {
        return TaustahakuApiFp(this.configuration).hakupalveluApiV2TaustahakuKohdeluokatPost(hakulausekeLisarajausKysely, tagi, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hae ehdot täyttäviä tieosia taustahakuna
     * @param {HakulausekeLisarajausKysely} hakulausekeLisarajausKysely 
     * @param {any} [tagi] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2TaustahakuTieosuudetPost(hakulausekeLisarajausKysely: HakulausekeLisarajausKysely, tagi?: any, options?: RawAxiosRequestConfig) {
        return TaustahakuApiFp(this.configuration).hakupalveluApiV2TaustahakuTieosuudetPost(hakulausekeLisarajausKysely, tagi, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hakee tehtyjen taustahakujen tilat.
     * @param {string} [tagit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2TaustahakuTilaGet(tagit?: string, options?: RawAxiosRequestConfig) {
        return TaustahakuApiFp(this.configuration).hakupalveluApiV2TaustahakuTilaGet(tagit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hakee taustahaun tilan annetulle hakutunnistelle.
     * @param {string} hakutunniste 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2TaustahakuTilaHakutunnisteGet(hakutunniste: string, options?: RawAxiosRequestConfig) {
        return TaustahakuApiFp(this.configuration).hakupalveluApiV2TaustahakuTilaHakutunnisteGet(hakutunniste, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Hakee taustahaun tulokset annetulle hakutunnistelle.
     * @param {string} hakutunniste 
     * @param {number} [alkupiste] 
     * @param {number} [maara] 
     * @param {boolean} [eiGeometrioita] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet(hakutunniste: string, alkupiste?: number, maara?: number, eiGeometrioita?: boolean, options?: RawAxiosRequestConfig) {
        return TaustahakuApiFp(this.configuration).hakupalveluApiV2TaustahakuTuloksetHakutunnisteGet(hakutunniste, alkupiste, maara, eiGeometrioita, options).then((request) => request(this.axios, this.basePath));
    }
}



